apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: erickgallani/fibonacci-multi-docker-test-client
      ports:
          - containerPort: 3000